line-length = 120

[lint]
select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # pyflakes
    "I",    # isort
    "N",    # pep8-naming
    "D",    # pydocstyle
    "UP",   # pyupgrade
    "B",    # flake8-bugbear
]
ignore = ["D203", "D213"]

[lint.pydocstyle]
convention = "google"

[format]
quote-style = "double"
indent-style = "space"
